package common

const (
	GSN_ALLOCATION_BATCH_SIZE = 100
	TRANSACTION_ID_ALLOCATION_BATCH_SIZE = 100
)

const (
	TRANSACTION_STATE_QUEUED = "QUEUED"
	TRANSACTION_STATE_COMMIT = "COMMIT"
	TRANSACTION_STATE_ROLLBACK = "ROLLBACK"
)

const (
	DB_OP_PUT = "PUT"
	DB_OP_DELETE = "DELETE"
	DB_OP_GET = "GET"
	DB_OP_BEGIN = "BEGIN"
	DB_OP_COMMIT = "COMMIT"
	DB_OP_ROLLBACK = "ROLLBACK"
)

const (
	TXN_ISOLATION_READ_COMMITTED   = "READ_COMMITTED"
	TXN_ISOLATION_REPEATABLE_READ  = "REPEATABLE_READ"
	TXN_ISOLATION_SERIALIZABLE     = "SERIALIZABLE"
)